services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: zile
      POSTGRES_PASSWORD: za
      POSTGRES_DB: fraud
    ports:
      - "5440:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # Main port
      - "15672:15672" # UI port (access at localhost:15672)

  # --- YOUR SERVICES (Skeletons) ---
  # We connect them to the same network so they can talk to 'postgres', 'redis', etc.
  web-server:
    build: ./services/web-server/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload
    volumes:
      - ./services/web-server/app:/app/app
    ports:
      - "7000:8000"
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq

  transaction-extraction-service:
    build: ./services/transaction_extraction/app
    container_name: transaction-extraction-service
    ports:
      ["7001:8000"]
    volumes:
      - ./services/transaction_extraction/app:/app/app
    environment:
      - ENV=development

  notification-service:
    build: ./services/notification_service/app
    container_name: notification-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload
    ports:
      ["7002:8000"]
    environment:
      - APP_NAME=NotificationService
    volumes:
      - ./services/notification_service/app:/app/app

  accounts-service:
    build: ./services/accounts/app
    container_name: accounts-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload
    ports:
      ["7003:8000"]
    environment:
      - APP_NAME=AccountsService
    volumes:
      - ./services/accounts/app:/app/app

  read_api:
    build: ./services/read_api/app
    container_name: read-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload
    ports:
      ["7004:8000"]
    environment:
      - APP_NAME=ReadAPI
      - DATABASE_URL=postgresql://zile:za@postgres/fraud
      - REDIS_HOST=redis
    volumes:
      - ./services/read_api/app:/app/app
    depends_on:
      - postgres
      - redis
