apiVersion: v1
kind: Service
metadata:
  name: transaction-extraction-service
  namespace: fraud-detection
spec:
  selector:
    app: transaction-extraction
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
